/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false functions/env.d.ts` (hash: 3db1208897f5a428269eb5daa4938153)
interface __BaseEnv_Env {
	GOOGLE_AUTH_DB: D1Database;
	APP_ORIGIN: string;
	ACCESS_ISSUER: string;
	ACCESS_AUD: string;
	GOOGLE_CLIENT_ID: string;
	VITE_GOOGLE_CLIENT_ID: string;
	YARN_ENABLE_IMMUTABLE_INSTALLS: string;
	VITE_GOOGLE_AUTH_BACKEND: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_TOKEN_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "ACCESS_ISSUER" | "ACCESS_AUD" | "GOOGLE_CLIENT_ID" | "VITE_GOOGLE_CLIENT_ID" | "YARN_ENABLE_IMMUTABLE_INSTALLS" | "VITE_GOOGLE_AUTH_BACKEND" | "GOOGLE_CLIENT_SECRET" | "GOOGLE_TOKEN_ENCRYPTION_KEY">> {}
}
