import { test, expect } from '@playwright/test';

test.use({ headless: true, baseURL: process.env.PLAYWRIGHT_BASE_URL ?? 'http://127.0.0.1:5175', launchOptions: { executablePath: process.env.PLAYWRIGHT_CHROME_EXECUTABLE } });

test('summary dialog selects previews, disables empty selection and saves generated summary', async ({ page }) => {
  const summaryMarkdown = '## Generated summary\n\n**Important**\n\n- First item\n- Second item';
  let finishSummary: (() => void) | undefined;
  let requests = 0;
  await page.route('https://summary.test/**', async route => {
    if (++requests === 1) return route.fulfill({ status: 503, body: 'Summary service unavailable' });
    await new Promise<void>(resolve => { finishSummary = resolve; });
    await route.fulfill({ json: { choices: [{ message: { content: summaryMarkdown } }] } });
  });
  await page.goto('/');
  await page.evaluate(async () => {
    const load = (path: string) => import(/* @vite-ignore */ path);
    const { default: store } = await load('/src/store/store.ts');
    const { addContent } = await load('/src/utils/contentStore.ts');
    const { generateDefaultChat } = await load('/src/constants/chat.ts');
    const { materializeActivePath } = await load('/src/utils/branchUtils.ts');
    const contentStore = {};
    const nodes = Object.fromEntries(['a', 'b', 'c'].map((id, index) => [id, { id, parentId: index ? ['a', 'b'][index - 1] : null, role: 'user', createdAt: index, contentHash: addContent(contentStore, [{ type: 'text', text: `Original ${id}` }]) }]));
    const tree = { nodes, rootId: 'a', activePath: ['a', 'b', 'c'] };
    const chat = { ...generateDefaultChat('Summary test'), branchTree: tree, messages: materializeActivePath(tree, contentStore) };
    chat.config.model = 'gpt-4o';
    store.getState().setOnboardingCompleted(true);
    store.setState({ chats: [chat], currentChatIndex: 0, contentStore, hideSideMenu: true, markdownMode: true, apiEndpoint: 'https://summary.test/v1/chat/completions', apiKey: 'test', providers: {}, favoriteModels: [], omittedNodeMaps: {}, generatingSessions: {} });
    document.documentElement.classList.add('dark');
  });
  const bubble = page.locator('[data-node-id="b"]').first();
  await bubble.hover();
  await bubble.getByRole('button', { name: '要約を作成', exact: true }).click();
  const modal = page.locator('#modal-root');
  const first = modal.getByRole('checkbox', { name: 'バブル1を要約に含める' });
  const second = modal.getByRole('checkbox', { name: 'バブル2を要約に含める' });
  await expect(second).toBeChecked();
  await expect(first).toBeDisabled();
  const generate = modal.getByRole('button', { name: '要約を生成', exact: true });
  await expect(generate).toBeEnabled();
  const previewStyle = (checkbox: typeof first) => checkbox.locator('..').evaluate(element => ({ color: getComputedStyle(element).color, border: getComputedStyle(element).borderColor }));
  const inactive = await previewStyle(first);
  const active = await previewStyle(second);
  expect(inactive.color).not.toBe(active.color);
  expect(inactive.border).not.toBe(active.border);
  await modal.getByRole('radio', { name: 'ここまで', exact: true }).check();
  await expect(first).toBeChecked();
  expect(await previewStyle(first)).toEqual(active);
  await modal.getByRole('radio', { name: '選択範囲', exact: true }).check();
  await expect(generate).toBeDisabled();
  await expect(generate).toHaveClass(/btn-neutral/);
  await expect(modal.getByText('要約するバブルを選択してください。', { exact: true })).toBeVisible();
  expect(await previewStyle(second)).toEqual(inactive);
  await second.check();
  await expect(generate).toBeEnabled();
  await first.check();
  await modal.getByRole('radio', { name: 'ここまで', exact: true }).check();
  await page.screenshot({ path: '/tmp/weavelet-summary-dialog-fixed.jpg' });
  await generate.click();
  await expect(modal.getByText('要約の対象を選択', { exact: true })).toHaveCount(0);
  await bubble.getByRole('button', { name: '要約失敗', exact: true }).click();
  await expect(modal.getByText('Summary service unavailable', { exact: true })).toBeVisible();
  await expect(generate).toBeEnabled();
  await generate.click();
  await expect(bubble.getByRole('status')).toContainText('要約中');
  await expect(bubble.getByRole('button', { name: /要約に含める|要約対象から外す/ })).toHaveCount(0);
  await expect(modal.getByText('要約の対象を選択', { exact: true })).toHaveCount(0);
  await page.mouse.move(0, 0);
  await expect(bubble.getByRole('status')).toBeVisible();
  const dots = bubble.getByRole('img', { name: '要約生成中' });
  const initialDots = await dots.textContent();
  await expect.poll(() => dots.textContent()).not.toBe(initialDots);
  await page.evaluate(async () => {
    const load = (path: string) => import(/* @vite-ignore */ path);
    const { default: store } = await load('/src/store/store.ts');
    const { generateDefaultChat } = await load('/src/constants/chat.ts');
    store.setState({ chats: [...store.getState().chats, generateDefaultChat('Other chat')], currentChatIndex: 1 });
  });
  await expect(page.getByRole('status').filter({ hasText: '要約中' })).toHaveCount(0);
  await page.evaluate(async () => { const { default: store } = await import(/* @vite-ignore */ '/src/store/store.ts'); store.setState({ currentChatIndex: 0 }); });
  await expect(bubble.getByRole('status')).toBeVisible();
  await bubble.getByRole('button', { name: '要約を作成', exact: true }).click();
  await expect(modal.getByRole('button', { name: '生成中…', exact: true })).toBeDisabled();
  await expect(modal.getByRole('radio', { name: 'ここまで', exact: true })).toBeChecked();
  await expect(first).toBeChecked();
  await expect(second).toBeChecked();
  await modal.getByRole('button', { name: '閉じる', exact: true }).click();
  expect(requests).toBe(2);
  finishSummary!();
  await expect(bubble.getByRole('status')).toHaveCount(0);
  await expect(modal.getByText('要約の対象を選択', { exact: true })).toHaveCount(0);
  await expect(page.getByText('Generated summary', { exact: true })).toBeVisible();
  const saved = await page.evaluate(async () => {
    const { default: store } = await import(/* @vite-ignore */ '/src/store/store.ts');
    return store.getState().chats[0].summaries;
  });
  expect(saved).toMatchObject([{ text: summaryMarkdown, useForSubmit: true, sources: [{ nodeId: 'a' }, { nodeId: 'b' }] }]);
  const capsule = bubble.getByRole('group', { name: '要約操作' });
  const originalButton = capsule.getByRole('button', { name: '原文', exact: true });
  const summaryButton = capsule.getByRole('button', { name: '要約', exact: true });
  await bubble.hover();
  const otherCapsule = bubble.getByRole('group', { name: 'バブル操作' });
  expect((await capsule.boundingBox())!.x + (await capsule.boundingBox())!.width).toBeLessThan((await otherCapsule.boundingBox())!.x);
  await expect(originalButton).toHaveAttribute('aria-pressed', 'false');
  await expect(summaryButton).toHaveAttribute('aria-pressed', 'true');
  await expect(capsule.getByRole('button', { name: '要約を作成', exact: true })).toHaveCount(0);
  await expect(bubble.getByRole('tablist')).toHaveCount(0);
  await expect(bubble.getByText('送信：', { exact: true })).toHaveCount(0);
  await expect(bubble.getByText(/概算.*トークン/)).toHaveCount(0);
  const summaryText = bubble.getByText('Generated summary', { exact: true });
  await expect(bubble.getByRole('heading', { name: 'Generated summary', level: 2 })).toBeVisible();
  await expect(bubble.locator('strong').filter({ hasText: 'Important' })).toBeVisible();
  await expect(bubble.getByRole('listitem')).toHaveText(['First item', 'Second item']);
  const summarySurface = bubble.locator('[data-summary-content]');
  const surface = await summarySurface.evaluate(element => ({ background: getComputedStyle(element).backgroundColor, color: getComputedStyle(element).color, border: getComputedStyle(element.closest('section')!).borderColor, width: getComputedStyle(element.closest('section')!).borderTopWidth }));
  expect(surface.background).toBe('rgba(32, 33, 35, 0.2)');
  expect(surface.color).toBe('rgb(236, 236, 241)');
  expect(surface.width).toBe('0px');
  const expandedHeight = (await summarySurface.boundingBox())!.height;
  await bubble.getByRole('button', { name: 'Collapse message', exact: true }).click();
  const summaryPreview = bubble.locator('[data-summary-preview]');
  await expect(summaryPreview).toBeVisible();
  await expect(summaryPreview).toHaveCSS('height', '72px');
  const collapsedHeight = (await summarySurface.boundingBox())!.height;
  expect(collapsedHeight).toBeLessThan(expandedHeight);
  await expect(summaryButton).toHaveAttribute('aria-pressed', 'true');
  await bubble.getByRole('button', { name: 'Expand message', exact: true }).click();
  await expect(summaryText).toBeVisible();
  await page.screenshot({ path: '/tmp/weavelet-summary-capsule-dark.jpg' });
  await originalButton.click();
  await expect(page.getByText('Original a', { exact: true })).toBeVisible();
  await expect(page.getByText('Original b', { exact: true })).toBeVisible();
  await bubble.getByRole('button', { name: 'Collapse message', exact: true }).click();
  const originalSurface = bubble.getByText('Original b', { exact: true }).locator('..');
  expect((await originalSurface.boundingBox())!.height).toBe(collapsedHeight);
  await bubble.getByRole('button', { name: 'Expand message', exact: true }).click();
  await expect(summaryText).toBeHidden();
  expect(await page.evaluate(async () => { const { default: store } = await import(/* @vite-ignore */ '/src/store/store.ts'); return store.getState().chats[0].summaries[0].useForSubmit; })).toBe(false);
  await summaryButton.click();
  expect(await page.evaluate(async () => { const { default: store } = await import(/* @vite-ignore */ '/src/store/store.ts'); return store.getState().chats[0].summaries[0].useForSubmit; })).toBe(true);
  await expect(summaryText).toBeVisible();
  await expect(page.getByText('Original a', { exact: true })).toBeHidden();
  await expect(bubble.getByText('送信：', { exact: true })).toHaveCount(0);
  await expect(bubble.getByText(/概算.*トークン/)).toHaveCount(0);
  await summaryButton.click();
  await expect(modal.getByText('要約の対象を選択', { exact: true })).toBeVisible();
  await expect(first).toBeChecked();
  await expect(second).toBeChecked();
  await generate.click();
  await expect(bubble.getByRole('status')).toBeVisible();
  await expect(summaryButton).toHaveCount(0);
  await expect(originalButton).toBeVisible();
  await expect(modal.getByText('要約の対象を選択', { exact: true })).toHaveCount(0);
  await expect.poll(() => requests).toBe(3);
  finishSummary!();
  await expect(bubble.getByRole('status')).toHaveCount(0);
  await expect(summaryButton).toBeVisible();
  await expect(summaryText).toBeVisible();
  const firstBubble = page.locator('[data-node-id="a"]').first();
  await firstBubble.hover();
  await firstBubble.getByRole('group', { name: '要約操作' }).getByRole('button', { name: '要約', exact: true }).click();
  await expect(first).toBeChecked();
  await expect(second).toBeChecked();
  await expect(generate).toBeEnabled();
  await modal.getByRole('button', { name: 'キャンセル', exact: true }).click();
  await page.evaluate(async () => { const { useSummaryDisplay } = await import(/* @vite-ignore */ '/src/components/Chat/ChatContent/Message/View/bubbleSummaryDisplay.ts'); useSummaryDisplay.setState({ chosen: {} }); });
  await expect(summaryText).toBeVisible();
  await expect(summaryButton).toHaveAttribute('aria-pressed', 'true');
  await page.evaluate(() => document.documentElement.classList.remove('dark'));
  await expect(summarySurface).toHaveCSS('color', 'rgb(52, 53, 65)');
  await expect(summarySurface).toHaveCSS('background-color', 'rgba(255, 255, 255, 0.6)');
  await page.screenshot({ path: '/tmp/weavelet-summary-capsule-light.jpg' });
});
